### ISSUE TITLE
ReferenceError: artifacts is not defined

### ISSUE THREAD

**Issue by amithanamakkanavar** [ConsenSys/truffle-webpack-demo#20]
## Issue

> truffle-webpack@0.0.1 start /home/kpit/Desktop/webpack_demo/truffle_webpack
> node ./scripts/start.js

Starting the development server...

[TRUFFLE SOLIDITY] Writing temporary contract build artifacts to /home/kpit/Desktop/webpack_demo/truffle_webpack/.truffle-solidity-loader
[TRUFFLE SOLIDITY] Compiling ConvertLib.sol...
[TRUFFLE SOLIDITY] Compiling MetaCoin.sol...
[TRUFFLE SOLIDITY] Writing artifacts to ./.truffle-solidity-loader
[TRUFFLE SOLIDITY] COMPILATION FINISHED
[TRUFFLE SOLIDITY] RUNNING MIGRATIONS
[TRUFFLE SOLIDITY] Running migration: 1_initial_migration.js

/home/kpit/Desktop/webpack_demo/truffle_webpack/migrations/1_initial_migration.js:1
var Migrations = artifacts.require("../contracts/Migrations.sol");
                 ^
ReferenceError: artifacts is not defined
    at /home/kpit/Desktop/webpack_demo/truffle_webpack/migrations/1_initial_migration.js:1:18
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at /home/kpit/Desktop/webpack_demo/truffle_webpack/node_modules/truffle/lib/require.js:78:14
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! truffle-webpack@0.0.1 start: `node ./scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the truffle-webpack@0.0.1 start script 'node ./scripts/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the truffle-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs truffle-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls truffle-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

## Steps to Reproduce

npm run start

* Operating System: Ubuntu 14.04 LTE
* Truffle version: 3.1.2
* Testrpc version: 3.0.3
* Ethereum client: geth
* node version: 6.10.0
* npm version: 3.10.10

**Comment by amithanamakkanavar** [comment]
some how found the solution
Do nor add "var Migrations = artifacts.require("../contracts/Migrations.sol");" thes in migration script.
